apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: {{ .Values.deployment.metadata.labels.app}}
spec:
  replicas: {{ .Values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.deployment.metadata.labels.app}}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.metadata.labels.app}}
    spec:
      containers:
      - name: flask
        image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: PORT
          value: "{{ .Values.service.targetPort }}"
        ports:
          - containerPort: {{ .Values.service.targetPort }}